### ISSUE TITLE
请问有没有完整的数据库脚本呀

### ISSUE THREAD

**Issue by ShoneKey** [pythonstock/stock#13]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/data/stock/web/dataTableHandler.py", line 136, in get
    stock_web_list = self.db.query(sql)
  File "/usr/local/lib/python3.6/site-packages/torndb.py", line 136, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/usr/local/lib/python3.6/site-packages/torndb.py", line 234, in _execute
    return cursor.execute(query, kwparameters or parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'stock_data.ts_stock_basics' doesn't exist")

**Comment by golangpkg** [comment]
这个是利用 pandas 动态创建的数据库。请下载下 最新的docker 镜像。
这个问题已经解决了。
