### ISSUE TITLE
作者你好，我在docker部署之后点击买入猜想有个小Bug 找不到表

### ISSUE THREAD

**Issue by aaronuu** [pythonstock/stock#15]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/data/stock/web/dataTableHandler.py", line 136, in get
    stock_web_list = self.db.query(sql)
  File "/usr/local/lib/python3.6/site-packages/torndb.py", line 136, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/usr/local/lib/python3.6/site-packages/torndb.py", line 234, in _execute
    return cursor.execute(query, kwparameters or parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'stock_data.guess_indicators_lite_buy_daily' doesn't exist")`

**Comment by golangpkg** [comment]
每天 18 点跑数据。 启动之后需要 15 20 分钟才能把历史数据跑完。
