### ISSUE TITLE
rm: cannot remove hist_data_cache,xxx : Is a directory

### ISSUE THREAD

**Issue by nickfan** [pythonstock/stock#28]
运行：

```sh
docker exec -it stock bash 
sh /data/stock/jobs/cron.daily/run_daily
```

报错：

```sh
NOTE: Behavior of MACDH calculation has changed as of July 2017 - it is now 1/2 of previous calculated values
Traceback (most recent call last):
  File "/data/stock/libs/common.py", line 160, in run_with_args
    run_fun(tmp_datetime_show)  # 使用当前时间
  File "/data/stock/jobs/guess_indicators_daily_job.py", line 124, in stat_all_batch
    stat_index_all(data, i)
  File "/data/stock/jobs/guess_indicators_daily_job.py", line 218, in stat_index_all
    data_new = concat_guess_data(stock_column, data)
  File "/data/stock/jobs/guess_indicators_daily_job.py", line 248, in concat_guess_data
    stock_guess = stock_guess.apply(apply_guess, stock_column=stock_column, axis=1)  # , axis=1)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/apply.py", line 313, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/apply.py", line 341, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/apply.py", line 113, in f
    return func(x, *args, **kwds)
  File "/data/stock/jobs/guess_indicators_daily_job.py", line 270, in apply_guess
    stock = common.get_hist_data_cache(code, date_start, date_end)
  File "/data/stock/libs/common.py", line 189, in get_hist_data_cache
    stock = ts.get_hist_data(code, start=date_start, end=date_end)
  File "/usr/local/lib/python3.6/site-packages/tushare/stock/trading.py", line 81, in get_hist_data
    js = json.loads(lines.decode('utf-8') if ct.PY3 else lines)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 78670 (char 78669)
rm -f /data/cache/hist_data_cache/2020-07/
rm: cannot remove '/data/cache/hist_data_cache/2020-07/': Is a directory
```

**Comment by zhenshigu** [comment]
rm -f /data/cache/hist_data_cache/2020-07/
rm: cannot remove '/data/cache/hist_data_cache/2020-07/': Is a directory

**Comment by nickfan** [comment]
我觉得是不是代码里应该把```rm -f ```换为```rm -rf```
json部分的报错就不知道了，是处理哪边不严格吗？
