### ISSUE TITLE
run_daily报错http error 456

### ISSUE THREAD

**Issue by SenYoung** [pythonstock/stock#29]
/data/stock/jobs/cron.daily/run_daily

Traceback (most recent call last):
  File "/data/stock/libs/common.py", line 160, in run_with_args
    run_fun(tmp_datetime_show)  # 使用当前时间
  File "/data/stock/jobs/18h_daily_job.py", line 49, in stat_today_all
    data = ts.get_today_all()
  File "/usr/local/lib/python3.6/site-packages/tushare/stock/trading.py", line 327, in get_today_all
    newdf = _parsing_dayprice_json('hs_a', i)
  File "/usr/local/lib/python3.6/site-packages/tushare/stock/trading.py", line 120, in _parsing_dayprice_json
    text = urlopen(request, timeout=10).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 456:

**Comment by guoleigl** [comment]
Traceback (most recent call last):
  File "/data/stock/libs/common.py", line 166, in run_with_args
    run_fun(tmp_datetime_show)  # 使用当前时间
  File "/data/stock/jobs/guess_indicators_daily_job.py", line 75, in stat_all_lite_sell
    data = pd.read_sql(sql=sql_1, con=common.engine(), params=[datetime_int])
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 527, in read_sql
    chunksize=chunksize,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1308, in read_query
    result = self.execute(*args)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1176, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3108, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1252, in execute
    future=False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1553, in _exec_driver_sql
    distilled_parameters,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'stock_data.guess_indicators_daily' doesn't exist")
[SQL: 
            SELECT `date`, `code`, `name`, `changepercent`, `trade`, `open`, `high`, `low`, 
                            `settlement`, `volume`, `turnoverratio`, `amount`, `per`, `pb`, `mktcap`,
                             `nmc` ,`kdjj`,`rsi_6`,`cci`
                        FROM stock_data.guess_indicators_daily WHERE `date` = %s 
                        and kdjk <= 20 and kdjd <= 30 and kdjj <= 10  and rsi_6 <= 20  and cci <= -100
    ]
[parameters: ('20210728',)]
(Background on this error at: http://sqlalche.me/e/14/f405)
rm -f /data/cache/hist_data_cache/2021-07/
