### ISSUE TITLE
执行run_daily脚本报错

### ISSUE THREAD

**Issue by smy0419** [pythonstock/stock#47]
root@c1ee33d1bbbb:/data# sh /data/stock/jobs/cron.daily/run_daily
Traceback (most recent call last):
  File "/data/stock/libs/common.py", line 160, in run_with_args
    run_fun(tmp_datetime_show)  # 使用当前时间
  File "/data/stock/jobs/daily_job.py", line 30, in stat_all
    data = ts.top_list(datetime_str)
  File "/usr/local/lib/python3.6/site-packages/tushare/stock/billboard.py", line 64, in top_list
    if(du.is_holiday(date)):
  File "/usr/local/lib/python3.6/site-packages/tushare/util/dateu.py", line 91, in is_holiday
    df = trade_cal()
  File "/usr/local/lib/python3.6/site-packages/tushare/util/dateu.py", line 83, in trade_cal
    df = pd.read_csv(ct.ALL_CAL_FILE)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/usr/local/lib/python3.6/site-packages/pandas/io/common.py", line 172, in get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/common.py", line 141, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by wyzhou007** [comment]
一样 启动 run_daily报错 有解决的方法吗

**Comment by smy0419** [comment]
> 一样 启动 run_daily报错 有解决的方法吗

若你没有使用docker-compose的方式部署的话，不需要执行run_daily。
昨天报错后没管它，今天看已经有数据了。

**Comment by wyzhou007** [comment]
> > 一样 启动 run_daily报错 有解决的方法吗
> 
> 若你没有使用docker-compose的方式部署的话，不需要执行run_daily。
> 昨天报错后没管它，今天看已经有数据了。

启动后，不用管吗，目前我登录系统看不到任何数据

**Comment by wyzhou007** [comment]
隔天才有数据么

**Comment by smy0419** [comment]
> 隔天才有数据么

是的，隔天才可以看到数据。
