### ISSUE TITLE
东财和新浪有数据，其他的出现连接拒绝是什么原因呢

### ISSUE THREAD

**Issue by jianxinH** [pythonstock/stock#87]
root@72337ee91d5b:/usr/local/lib/python3.7/logging# sh /data/stock/jobs/cron.daily/run_daily
Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by bg4xsd** [comment]
把 run_daily 里面的命令拆开 ， 看看问题出在哪里？ 看这样在是网络不通。

**Comment by bg4xsd** [comment]
实在不行就直接 用 akshare，去抓数据回来自己做图吧。 也不是太麻烦。用了几天，这个系统的功能比较简单， 是个不错的框架，如何你动手能力强就自己拆开修改部署吧。 核心的代码都共享出来了。 跳开 docker自己部署也很方便。

**Comment by jianxinH** [comment]
想问一下这是网络问题吗？还是要修改配置文件

root@68fabe4af94a:/data# sh /data/stock/jobs/cron.daily/run_daily
Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by bg4xsd** [comment]
看你这提示是网络不通， 刚才去翻了一下历史数据， 的确也缺少这两个数据； 估计是这两个网站有了变化吧。刚刚已经卸载了， 准备在 django 上自己慢慢折腾了。 建议大家就看看源码， 了解一下作者的思路即可，源码都在 python的文件里面。 不要花费太多时间去搭建这个软件了。 真的里面没有啥功能。
